// <auto-generated />
using System;
using MegisEbys.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegisEbys.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250805174813_AddKullaniciAndEvrakModels")]
    partial class AddKullaniciAndEvrakModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MegisEbys.Api.Models.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Evrak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("EvrakNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvrakTuruId")
                        .HasColumnType("int");

                    b.Property<string>("IlgiliKurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SorumluBirimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("Yonu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvrakTuruId");

                    b.HasIndex("SorumluBirimId");

                    b.ToTable("Evraklar");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.EvrakTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EvrakTurleri");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yetki")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Evrak", b =>
                {
                    b.HasOne("MegisEbys.Api.Models.EvrakTuru", "EvrakTuru")
                        .WithMany()
                        .HasForeignKey("EvrakTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MegisEbys.Api.Models.Birim", "SorumluBirim")
                        .WithMany()
                        .HasForeignKey("SorumluBirimId");

                    b.Navigation("EvrakTuru");

                    b.Navigation("SorumluBirim");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Kullanici", b =>
                {
                    b.HasOne("MegisEbys.Api.Models.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.Navigation("Birim");
                });
#pragma warning restore 612, 618
        }
    }
}
