// <auto-generated />
using System;
using MegisEbys.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegisEbys.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250810063304_AddIslemGecmisi")]
    partial class AddIslemGecmisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MegisEbys.Api.Models.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.DisDepartman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KurumId");

                    b.ToTable("DisDepartmanlar");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.DisKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisDepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisDepartmanId");

                    b.ToTable("DisKullanicilar");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Evrak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AliciBirimId")
                        .HasColumnType("int");

                    b.Property<int?>("AliciKullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("DahiliMi")
                        .HasColumnType("bit");

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("EvrakNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvrakTuruId")
                        .HasColumnType("int");

                    b.Property<int?>("GonderenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("IlgiliKurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SorumluBirimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("Yonu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AliciBirimId");

                    b.HasIndex("AliciKullaniciId");

                    b.HasIndex("EvrakTuruId");

                    b.HasIndex("GonderenKullaniciId");

                    b.HasIndex("SorumluBirimId");

                    b.ToTable("Evraklar");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.EvrakTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EvrakTurleri");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.IslemGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvrakId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvrakId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.IzinTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("TalepEdenKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TalepEdenKullaniciId");

                    b.ToTable("IzinTalepleri");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yetki")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Kurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kurumlar");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.DisDepartman", b =>
                {
                    b.HasOne("MegisEbys.Api.Models.Kurum", "Kurum")
                        .WithMany("Departmanlar")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.DisKullanici", b =>
                {
                    b.HasOne("MegisEbys.Api.Models.DisDepartman", "DisDepartman")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("DisDepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisDepartman");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Evrak", b =>
                {
                    b.HasOne("MegisEbys.Api.Models.Birim", "AliciBirim")
                        .WithMany()
                        .HasForeignKey("AliciBirimId");

                    b.HasOne("MegisEbys.Api.Models.Kullanici", "AliciKullanici")
                        .WithMany()
                        .HasForeignKey("AliciKullaniciId");

                    b.HasOne("MegisEbys.Api.Models.EvrakTuru", "EvrakTuru")
                        .WithMany()
                        .HasForeignKey("EvrakTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MegisEbys.Api.Models.Kullanici", "GonderenKullanici")
                        .WithMany()
                        .HasForeignKey("GonderenKullaniciId");

                    b.HasOne("MegisEbys.Api.Models.Birim", "SorumluBirim")
                        .WithMany()
                        .HasForeignKey("SorumluBirimId");

                    b.Navigation("AliciBirim");

                    b.Navigation("AliciKullanici");

                    b.Navigation("EvrakTuru");

                    b.Navigation("GonderenKullanici");

                    b.Navigation("SorumluBirim");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.IslemGecmisi", b =>
                {
                    b.HasOne("MegisEbys.Api.Models.Evrak", "Evrak")
                        .WithMany()
                        .HasForeignKey("EvrakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MegisEbys.Api.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Evrak");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.IzinTalebi", b =>
                {
                    b.HasOne("MegisEbys.Api.Models.Kullanici", "TalepEdenKullanici")
                        .WithMany()
                        .HasForeignKey("TalepEdenKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalepEdenKullanici");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Kullanici", b =>
                {
                    b.HasOne("MegisEbys.Api.Models.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.DisDepartman", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("MegisEbys.Api.Models.Kurum", b =>
                {
                    b.Navigation("Departmanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
